name: FlyTicket
main: FlyTicket\Main
api: 5.0.0
version: 3
author: 
- ayd4ndemirci
- AmitxD
permissions:
  flyticket.command.use:
    description: "Allows the user to run open Flyticket"
    default: true